apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: products-api
  description: CRUD API for managing products
  annotations:
    github.com/project-slug: Egregiuss/backstage-api-specs
spec:
  type: openapi
  lifecycle: experimental
  owner: user:guest
  definition: |
    openapi: 3.0.3
    info:
      title: Products API
      description: CRUD API for managing products
      version: 1.0.0
---
apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: football-results-api
  description: API for football fixtures, scores, teams and standings
  annotations:
    github.com/project-slug: Egregiuss/backstage-api-specs
spec:
  type: openapi
  lifecycle: experimental
  owner: user:guest
  definition: |
    openapi: 3.0.3
    info:
      title: Football Results API
      description: API for football fixtures, scores, teams and standings
      version: 1.0.0
